//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod schedule_bulk;
pub mod schedule_employee_bulk;
pub mod schedule_organization_bulk;
pub mod schedule_weekday_bulk;

pub use schedule_bulk::ScheduleBulkService;
pub use schedule_employee_bulk::ScheduleEmployeeBulkService;
pub use schedule_organization_bulk::ScheduleOrganizationBulkService;
pub use schedule_weekday_bulk::ScheduleWeekdayBulkService;

// <<< CUSTOM
// END CUSTOM
