//! Bulk operations for ScheduleEmployee entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateScheduleEmployeeDto;
use crate::application::service::ScheduleEmployeeService;
use crate::domain::entity::ScheduleEmployee;

/// Bulk operation handler for ScheduleEmployee entities.
///
/// Wraps `ScheduleEmployeeService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ScheduleEmployeeBulkService = GenericBulkService<ScheduleEmployee, CreateScheduleEmployeeDto, ScheduleEmployeeService>;

// <<< CUSTOM
// END CUSTOM
