//! Bulk operations for ScheduleWeekday entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateScheduleWeekdayDto;
use crate::application::service::ScheduleWeekdayService;
use crate::domain::entity::ScheduleWeekday;

/// Bulk operation handler for ScheduleWeekday entities.
///
/// Wraps `ScheduleWeekdayService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ScheduleWeekdayBulkService = GenericBulkService<ScheduleWeekday, CreateScheduleWeekdayDto, ScheduleWeekdayService>;

// <<< CUSTOM
// END CUSTOM
