//! Bulk operations for Schedule entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateScheduleDto;
use crate::application::service::ScheduleService;
use crate::domain::entity::Schedule;

/// Bulk operation handler for Schedule entities.
///
/// Wraps `ScheduleService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ScheduleBulkService = GenericBulkService<Schedule, CreateScheduleDto, ScheduleService>;

// <<< CUSTOM
// END CUSTOM
