//! Bulk operations for ScheduleOrganization entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateScheduleOrganizationDto;
use crate::application::service::ScheduleOrganizationService;
use crate::domain::entity::ScheduleOrganization;

/// Bulk operation handler for ScheduleOrganization entities.
///
/// Wraps `ScheduleOrganizationService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ScheduleOrganizationBulkService = GenericBulkService<ScheduleOrganization, CreateScheduleOrganizationDto, ScheduleOrganizationService>;

// <<< CUSTOM
// END CUSTOM
