//! ScheduleWeekday DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ScheduleWeekday;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::WeekdayType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ScheduleWeekday
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateScheduleWeekdayDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "schedule_id")]
    pub schedule_id: Uuid,
    pub sun: WeekdayType,
    pub mon: WeekdayType,
    pub tue: WeekdayType,
    pub wed: WeekdayType,
    pub thu: WeekdayType,
    pub fri: WeekdayType,
    pub sat: WeekdayType,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ScheduleWeekday
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateScheduleWeekdayDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "schedule_id")]
    pub schedule_id: Uuid,
    pub sun: WeekdayType,
    pub mon: WeekdayType,
    pub tue: WeekdayType,
    pub wed: WeekdayType,
    pub thu: WeekdayType,
    pub fri: WeekdayType,
    pub sat: WeekdayType,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ScheduleWeekday
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchScheduleWeekdayDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "schedule_id")]
    pub schedule_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sun: Option<WeekdayType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mon: Option<WeekdayType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tue: Option<WeekdayType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wed: Option<WeekdayType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thu: Option<WeekdayType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fri: Option<WeekdayType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sat: Option<WeekdayType>,
}

impl PatchScheduleWeekdayDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.schedule_id.is_some() || self.sun.is_some() || self.mon.is_some() || self.tue.is_some() || self.wed.is_some() || self.thu.is_some() || self.fri.is_some() || self.sat.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ScheduleWeekday entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ScheduleWeekdayResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub schedule_id: Uuid,
    pub sun: WeekdayType,
    pub mon: WeekdayType,
    pub tue: WeekdayType,
    pub wed: WeekdayType,
    pub thu: WeekdayType,
    pub fri: WeekdayType,
    pub sat: WeekdayType,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ScheduleWeekday entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ScheduleWeekdayListResponseDto {
    /// List of items
    pub items: Vec<ScheduleWeekdayResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ScheduleWeekdayListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ScheduleWeekdayResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ScheduleWeekdaySummaryDto {
    pub id: Uuid,
    pub schedule_id: Uuid,
    pub sun: WeekdayType,
    pub mon: WeekdayType,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ScheduleWeekday> for ScheduleWeekdayResponseDto {
    fn from(entity: ScheduleWeekday) -> Self {
        Self {
            id: entity.id,
            schedule_id: entity.schedule_id,
            sun: entity.sun,
            mon: entity.mon,
            tue: entity.tue,
            wed: entity.wed,
            thu: entity.thu,
            fri: entity.fri,
            sat: entity.sat,
            metadata: entity.metadata,
        }
    }
}

impl From<ScheduleWeekday> for ScheduleWeekdaySummaryDto {
    fn from(entity: ScheduleWeekday) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            schedule_id: entity.schedule_id,
            sun: entity.sun,
            mon: entity.mon,
            created_at,
        }
    }
}

impl From<CreateScheduleWeekdayDto> for ScheduleWeekday {
    fn from(dto: CreateScheduleWeekdayDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            schedule_id: dto.schedule_id,
            sun: dto.sun,
            mon: dto.mon,
            tue: dto.tue,
            wed: dto.wed,
            thu: dto.thu,
            fri: dto.fri,
            sat: dto.sat,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ScheduleWeekday> for ScheduleWeekdayResponseDto {
    fn from(entity: &ScheduleWeekday) -> Self {
        Self {
            id: entity.id.clone(),
            schedule_id: entity.schedule_id.clone(),
            sun: entity.sun.clone(),
            mon: entity.mon.clone(),
            tue: entity.tue.clone(),
            wed: entity.wed.clone(),
            thu: entity.thu.clone(),
            fri: entity.fri.clone(),
            sat: entity.sat.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateScheduleWeekdayDto> for ScheduleWeekday {
    fn from_create_dto(dto: CreateScheduleWeekdayDto) -> backbone_core::ServiceResult<Self> {
        Ok(ScheduleWeekday::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateScheduleWeekdayDto> for ScheduleWeekday {
    fn apply_update(mut self, dto: UpdateScheduleWeekdayDto) -> backbone_core::ServiceResult<Self> {
        self.schedule_id = dto.schedule_id;
        self.sun = dto.sun;
        self.mon = dto.mon;
        self.tue = dto.tue;
        self.wed = dto.wed;
        self.thu = dto.thu;
        self.fri = dto.fri;
        self.sat = dto.sat;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ScheduleWeekday here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
