//! ScheduleEmployee DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate, NaiveTime};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ScheduleEmployee;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ScheduleEmployee
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateScheduleEmployeeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "schedule_date")]
    pub schedule_date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "order_number")]
    pub order_number: i32,
    #[serde(alias = "time_in")]
    pub time_in: NaiveTime,
    #[serde(alias = "time_out")]
    pub time_out: NaiveTime,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ScheduleEmployee
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateScheduleEmployeeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "schedule_date")]
    pub schedule_date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "order_number")]
    pub order_number: i32,
    #[serde(alias = "time_in")]
    pub time_in: NaiveTime,
    #[serde(alias = "time_out")]
    pub time_out: NaiveTime,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ScheduleEmployee
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchScheduleEmployeeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "schedule_date")]
    pub schedule_date: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "order_number")]
    pub order_number: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "time_in")]
    pub time_in: Option<NaiveTime>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "time_out")]
    pub time_out: Option<NaiveTime>,
}

impl PatchScheduleEmployeeDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.schedule_date.is_some() || self.order_number.is_some() || self.time_in.is_some() || self.time_out.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ScheduleEmployee entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ScheduleEmployeeResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub schedule_date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub order_number: i32,
    pub time_in: NaiveTime,
    pub time_out: NaiveTime,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ScheduleEmployee entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ScheduleEmployeeListResponseDto {
    /// List of items
    pub items: Vec<ScheduleEmployeeResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ScheduleEmployeeListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ScheduleEmployeeResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ScheduleEmployeeSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub schedule_date: NaiveDate,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ScheduleEmployee> for ScheduleEmployeeResponseDto {
    fn from(entity: ScheduleEmployee) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            schedule_date: entity.schedule_date,
            order_number: entity.order_number,
            time_in: entity.time_in,
            time_out: entity.time_out,
            metadata: entity.metadata,
        }
    }
}

impl From<ScheduleEmployee> for ScheduleEmployeeSummaryDto {
    fn from(entity: ScheduleEmployee) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            schedule_date: entity.schedule_date,
            created_at,
        }
    }
}

impl From<CreateScheduleEmployeeDto> for ScheduleEmployee {
    fn from(dto: CreateScheduleEmployeeDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            employee_id: dto.employee_id,
            schedule_date: dto.schedule_date,
            order_number: dto.order_number,
            time_in: dto.time_in,
            time_out: dto.time_out,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ScheduleEmployee> for ScheduleEmployeeResponseDto {
    fn from(entity: &ScheduleEmployee) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            employee_id: entity.employee_id.clone(),
            schedule_date: entity.schedule_date.clone(),
            order_number: entity.order_number.clone(),
            time_in: entity.time_in.clone(),
            time_out: entity.time_out.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateScheduleEmployeeDto> for ScheduleEmployee {
    fn from_create_dto(dto: CreateScheduleEmployeeDto) -> backbone_core::ServiceResult<Self> {
        Ok(ScheduleEmployee::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateScheduleEmployeeDto> for ScheduleEmployee {
    fn apply_update(mut self, dto: UpdateScheduleEmployeeDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.employee_id = dto.employee_id;
        self.schedule_date = dto.schedule_date;
        self.order_number = dto.order_number;
        self.time_in = dto.time_in;
        self.time_out = dto.time_out;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ScheduleEmployee here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

