//! ScheduleOrganization DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate, NaiveTime};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ScheduleOrganization;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ScheduleOrganization
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateScheduleOrganizationDto {
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "structure_id")]
    pub structure_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "order_number")]
    pub order_number: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "start_date")]
    pub start_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "end_date")]
    pub end_date: Option<NaiveDate>,
    #[serde(alias = "time_in")]
    pub time_in: NaiveTime,
    #[serde(alias = "time_out")]
    pub time_out: NaiveTime,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ScheduleOrganization
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateScheduleOrganizationDto {
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "structure_id")]
    pub structure_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "order_number")]
    pub order_number: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "start_date")]
    pub start_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "end_date")]
    pub end_date: Option<NaiveDate>,
    #[serde(alias = "time_in")]
    pub time_in: NaiveTime,
    #[serde(alias = "time_out")]
    pub time_out: NaiveTime,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ScheduleOrganization
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchScheduleOrganizationDto {
    #[serde(skip_serializing_if = "Option::is_none", alias = "structure_id")]
    pub structure_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "order_number")]
    pub order_number: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "start_date")]
    pub start_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "end_date")]
    pub end_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "time_in")]
    pub time_in: Option<NaiveTime>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "time_out")]
    pub time_out: Option<NaiveTime>,
}

impl PatchScheduleOrganizationDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.structure_id.is_some() || self.name.is_some() || self.order_number.is_some() || self.start_date.is_some() || self.end_date.is_some() || self.time_in.is_some() || self.time_out.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ScheduleOrganization entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ScheduleOrganizationResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    pub structure_id: Option<Uuid>,
    pub name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub order_number: i32,
    pub start_date: Option<NaiveDate>,
    pub end_date: Option<NaiveDate>,
    pub time_in: NaiveTime,
    pub time_out: NaiveTime,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ScheduleOrganization entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ScheduleOrganizationListResponseDto {
    /// List of items
    pub items: Vec<ScheduleOrganizationResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ScheduleOrganizationListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ScheduleOrganizationResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ScheduleOrganizationSummaryDto {
    pub id: Uuid,
    pub structure_id: Option<Uuid>,
    pub name: Option<String>,
    pub order_number: i32,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ScheduleOrganization> for ScheduleOrganizationResponseDto {
    fn from(entity: ScheduleOrganization) -> Self {
        Self {
            id: entity.id,
            structure_id: entity.structure_id,
            name: entity.name,
            order_number: entity.order_number,
            start_date: entity.start_date,
            end_date: entity.end_date,
            time_in: entity.time_in,
            time_out: entity.time_out,
            metadata: entity.metadata,
        }
    }
}

impl From<ScheduleOrganization> for ScheduleOrganizationSummaryDto {
    fn from(entity: ScheduleOrganization) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            structure_id: entity.structure_id,
            name: entity.name,
            order_number: entity.order_number,
            created_at,
        }
    }
}

impl From<CreateScheduleOrganizationDto> for ScheduleOrganization {
    fn from(dto: CreateScheduleOrganizationDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            structure_id: dto.structure_id,
            name: dto.name,
            order_number: dto.order_number,
            start_date: dto.start_date,
            end_date: dto.end_date,
            time_in: dto.time_in,
            time_out: dto.time_out,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ScheduleOrganization> for ScheduleOrganizationResponseDto {
    fn from(entity: &ScheduleOrganization) -> Self {
        Self {
            id: entity.id.clone(),
            structure_id: entity.structure_id.clone(),
            name: entity.name.clone(),
            order_number: entity.order_number.clone(),
            start_date: entity.start_date.clone(),
            end_date: entity.end_date.clone(),
            time_in: entity.time_in.clone(),
            time_out: entity.time_out.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateScheduleOrganizationDto> for ScheduleOrganization {
    fn from_create_dto(dto: CreateScheduleOrganizationDto) -> backbone_core::ServiceResult<Self> {
        Ok(ScheduleOrganization::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateScheduleOrganizationDto> for ScheduleOrganization {
    fn apply_update(mut self, dto: UpdateScheduleOrganizationDto) -> backbone_core::ServiceResult<Self> {
        self.structure_id = dto.structure_id;
        self.name = dto.name;
        self.order_number = dto.order_number;
        self.start_date = dto.start_date;
        self.end_date = dto.end_date;
        self.time_in = dto.time_in;
        self.time_out = dto.time_out;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ScheduleOrganization here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
