//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod schedule_specification;
pub mod schedule_employee_specification;
pub mod schedule_organization_specification;
pub mod schedule_weekday_specification;

// <<< CUSTOM
// END CUSTOM
