//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod schedule_domain_policy;
pub mod schedule_employee_domain_policy;
pub mod schedule_organization_domain_policy;
pub mod schedule_weekday_domain_policy;

pub use schedule_domain_policy::ScheduleDomainPolicy;
pub use schedule_employee_domain_policy::ScheduleEmployeeDomainPolicy;
pub use schedule_organization_domain_policy::ScheduleOrganizationDomainPolicy;
pub use schedule_weekday_domain_policy::ScheduleWeekdayDomainPolicy;

// <<< CUSTOM
// END CUSTOM
