//! Domain policy for ScheduleWeekday aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::ScheduleWeekday;

/// Domain policy for ScheduleWeekday — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<ScheduleWeekday>` in the `// <<< CUSTOM` zone.
pub type ScheduleWeekdayDomainPolicy = PermitAllPolicy<ScheduleWeekday>;

// <<< CUSTOM
// END CUSTOM
