//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod schedule_service;
pub mod schedule_employee_service;
pub mod schedule_organization_service;
pub mod schedule_weekday_service;

// <<< CUSTOM
// END CUSTOM

pub use schedule_service::ScheduleService;
pub use schedule_employee_service::ScheduleEmployeeService;
pub use schedule_organization_service::ScheduleOrganizationService;
pub use schedule_weekday_service::ScheduleWeekdayService;
// <<< CUSTOM
// END CUSTOM
