//! Application service for ScheduleWeekday entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `schedule_weekday_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateScheduleWeekdayDto, UpdateScheduleWeekdayDto};
use crate::domain::entity::ScheduleWeekday;
use crate::infrastructure::persistence::ScheduleWeekdayRepository;

/// Application service for ScheduleWeekday entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `schedule_weekday_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ScheduleWeekdayServiceCustom {
///     inner: Arc<ScheduleWeekdayService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ScheduleWeekdayService = GenericCrudService<
    ScheduleWeekday,
    CreateScheduleWeekdayDto,
    UpdateScheduleWeekdayDto,
    ScheduleWeekdayRepository,
>;

// <<< CUSTOM
// END CUSTOM
