//! Application service for ScheduleOrganization entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `schedule_organization_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateScheduleOrganizationDto, UpdateScheduleOrganizationDto};
use crate::domain::entity::ScheduleOrganization;
use crate::infrastructure::persistence::ScheduleOrganizationRepository;

/// Application service for ScheduleOrganization entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `schedule_organization_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ScheduleOrganizationServiceCustom {
///     inner: Arc<ScheduleOrganizationService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ScheduleOrganizationService = GenericCrudService<
    ScheduleOrganization,
    CreateScheduleOrganizationDto,
    UpdateScheduleOrganizationDto,
    ScheduleOrganizationRepository,
>;

// <<< CUSTOM
// END CUSTOM
