//! Application service for ScheduleEmployee entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `schedule_employee_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateScheduleEmployeeDto, UpdateScheduleEmployeeDto};
use crate::domain::entity::ScheduleEmployee;
use crate::infrastructure::persistence::ScheduleEmployeeRepository;

/// Application service for ScheduleEmployee entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `schedule_employee_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ScheduleEmployeeServiceCustom {
///     inner: Arc<ScheduleEmployeeService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ScheduleEmployeeService = GenericCrudService<
    ScheduleEmployee,
    CreateScheduleEmployeeDto,
    UpdateScheduleEmployeeDto,
    ScheduleEmployeeRepository,
>;

// <<< CUSTOM
// END CUSTOM
