-- ScheduleOrganization Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the schedule.schedule_organizations table.
-- Customize this file to add your initial data.

-- INSERT INTO schedule.schedule_organizations (
--     id,
--     company_id,
--     structure_id,
--     name,
--     order_number,
--     start_date,
--     end_date,
--     time_in,
--     time_out,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO schedule.schedule_organizations (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

