-- ScheduleWeekday Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the schedule.schedule_weekdays table.
-- Customize this file to add your initial data.

-- INSERT INTO schedule.schedule_weekdays (
--     id,
--     schedule_id,
--     sun,
--     mon,
--     tue,
--     wed,
--     thu,
--     fri,
--     sat,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO schedule.schedule_weekdays (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

