-- Revert the ADR-0014 strict company fence for schedule module (Wave 1 P0 sweep).
-- Generated by metaphor-schema.
DROP POLICY IF EXISTS schedule_employees_company_isolation ON schedule.schedule_employees;
ALTER TABLE schedule.schedule_employees NO FORCE ROW LEVEL SECURITY;
ALTER TABLE schedule.schedule_employees DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS schedule_organizations_company_isolation ON schedule.schedule_organizations;
ALTER TABLE schedule.schedule_organizations NO FORCE ROW LEVEL SECURITY;
ALTER TABLE schedule.schedule_organizations DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS schedules_company_isolation ON schedule.schedules;
ALTER TABLE schedule.schedules NO FORCE ROW LEVEL SECURITY;
ALTER TABLE schedule.schedules DISABLE ROW LEVEL SECURITY;
