-- Audit Triggers Migration for schedule module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Schedule (schedule.schedules)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION schedule.schedules_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS schedules_insert_audit ON schedule.schedules;
CREATE TRIGGER schedules_insert_audit BEFORE INSERT ON schedule.schedules
    FOR EACH ROW EXECUTE FUNCTION schedule.schedules_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS schedules_update_audit ON schedule.schedules;
CREATE TRIGGER schedules_update_audit BEFORE UPDATE ON schedule.schedules
    FOR EACH ROW EXECUTE FUNCTION schedule.schedules_audit_timestamp();

-- ==============================================================================
-- Table: ScheduleEmployee (schedule.schedule_employees)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION schedule.schedule_employees_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS schedule_employees_insert_audit ON schedule.schedule_employees;
CREATE TRIGGER schedule_employees_insert_audit BEFORE INSERT ON schedule.schedule_employees
    FOR EACH ROW EXECUTE FUNCTION schedule.schedule_employees_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS schedule_employees_update_audit ON schedule.schedule_employees;
CREATE TRIGGER schedule_employees_update_audit BEFORE UPDATE ON schedule.schedule_employees
    FOR EACH ROW EXECUTE FUNCTION schedule.schedule_employees_audit_timestamp();

-- ==============================================================================
-- Table: ScheduleOrganization (schedule.schedule_organizations)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION schedule.schedule_organizations_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS schedule_organizations_insert_audit ON schedule.schedule_organizations;
CREATE TRIGGER schedule_organizations_insert_audit BEFORE INSERT ON schedule.schedule_organizations
    FOR EACH ROW EXECUTE FUNCTION schedule.schedule_organizations_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS schedule_organizations_update_audit ON schedule.schedule_organizations;
CREATE TRIGGER schedule_organizations_update_audit BEFORE UPDATE ON schedule.schedule_organizations
    FOR EACH ROW EXECUTE FUNCTION schedule.schedule_organizations_audit_timestamp();

-- ==============================================================================
-- Table: ScheduleWeekday (schedule.schedule_weekdays)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION schedule.schedule_weekdays_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS schedule_weekdays_insert_audit ON schedule.schedule_weekdays;
CREATE TRIGGER schedule_weekdays_insert_audit BEFORE INSERT ON schedule.schedule_weekdays
    FOR EACH ROW EXECUTE FUNCTION schedule.schedule_weekdays_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS schedule_weekdays_update_audit ON schedule.schedule_weekdays;
CREATE TRIGGER schedule_weekdays_update_audit BEFORE UPDATE ON schedule.schedule_weekdays
    FOR EACH ROW EXECUTE FUNCTION schedule.schedule_weekdays_audit_timestamp();

