-- Company fence posture for schedule module (ADR-0014: strict)
-- Generated by metaphor-schema. Every entity here carries company_id and is fenced
-- strict: a session sees only rows whose company_id equals the request-scoped
-- company (`set_config('app.company_id', <uuid>, true)`); an unset var sees zero
-- rows (fail-closed). These tables shipped company_id without a policy since the
-- pre-ADR-0014 policy cleanup; this migration installs the declared fence
-- (Wave 1 P0 sweep, 2026-08-16). Requires the app to connect as a non-superuser
-- role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for schedule.schedule_employees
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE schedule.schedule_employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedule.schedule_employees FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS schedule_employees_company_isolation ON schedule.schedule_employees;
CREATE POLICY schedule_employees_company_isolation ON schedule.schedule_employees
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for schedule.schedule_organizations
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE schedule.schedule_organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedule.schedule_organizations FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS schedule_organizations_company_isolation ON schedule.schedule_organizations;
CREATE POLICY schedule_organizations_company_isolation ON schedule.schedule_organizations
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for schedule.schedules
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE schedule.schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedule.schedules FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS schedules_company_isolation ON schedule.schedules;
CREATE POLICY schedules_company_isolation ON schedule.schedules
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);
