-- Migration: Create schedule_employees table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS schedule;

CREATE TABLE IF NOT EXISTS schedule.schedule_employees (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    schedule_date DATE NOT NULL,
    order_number INTEGER NOT NULL DEFAULT 0,
    time_in TIME NOT NULL,
    time_out TIME NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_schedule_employees_employee_id_schedule_date ON schedule.schedule_employees (employee_id, schedule_date);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_schedule_employees_metadata_gin ON schedule.schedule_employees USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_schedule_employees_metadata_deleted_at ON schedule.schedule_employees ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_schedule_employees_metadata_created_at ON schedule.schedule_employees ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_schedule_employees_metadata_updated_at ON schedule.schedule_employees ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION schedule.schedule_employees_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS schedule_employees_insert_audit ON schedule.schedule_employees;
CREATE TRIGGER schedule_employees_insert_audit BEFORE INSERT ON schedule.schedule_employees
    FOR EACH ROW EXECUTE FUNCTION schedule.schedule_employees_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS schedule_employees_update_audit ON schedule.schedule_employees;
CREATE TRIGGER schedule_employees_update_audit BEFORE UPDATE ON schedule.schedule_employees
    FOR EACH ROW EXECUTE FUNCTION schedule.schedule_employees_audit_timestamp();
