-- Enum types for schedule module
-- Generated by metaphor-schema

-- Create weekday_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'weekday_type') THEN
        CREATE TYPE weekday_type AS ENUM ('weekday', 'weekend');
    END IF;
END
$$;

