-- Migration: Create schedule_weekdays table
-- Generated by metaphor-schema

-- Create weekday_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'weekday_type') THEN
        CREATE TYPE weekday_type AS ENUM ('weekday', 'weekend');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS schedule;

CREATE TABLE IF NOT EXISTS schedule.schedule_weekdays (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    schedule_id UUID NOT NULL,
    sun weekday_type NOT NULL DEFAULT 'weekend',
    mon weekday_type NOT NULL DEFAULT 'weekday',
    tue weekday_type NOT NULL DEFAULT 'weekday',
    wed weekday_type NOT NULL DEFAULT 'weekday',
    thu weekday_type NOT NULL DEFAULT 'weekday',
    fri weekday_type NOT NULL DEFAULT 'weekday',
    sat weekday_type NOT NULL DEFAULT 'weekend',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_schedule_weekdays_schedule_id ON schedule.schedule_weekdays (schedule_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_schedule_weekdays_metadata_gin ON schedule.schedule_weekdays USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_schedule_weekdays_metadata_deleted_at ON schedule.schedule_weekdays ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_schedule_weekdays_metadata_created_at ON schedule.schedule_weekdays ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_schedule_weekdays_metadata_updated_at ON schedule.schedule_weekdays ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION schedule.schedule_weekdays_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS schedule_weekdays_insert_audit ON schedule.schedule_weekdays;
CREATE TRIGGER schedule_weekdays_insert_audit BEFORE INSERT ON schedule.schedule_weekdays
    FOR EACH ROW EXECUTE FUNCTION schedule.schedule_weekdays_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS schedule_weekdays_update_audit ON schedule.schedule_weekdays;
CREATE TRIGGER schedule_weekdays_update_audit BEFORE UPDATE ON schedule.schedule_weekdays
    FOR EACH ROW EXECUTE FUNCTION schedule.schedule_weekdays_audit_timestamp();
