//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod schedule_events;
pub mod schedule_event_handlers;
pub mod schedule_employee_events;
pub mod schedule_employee_event_handlers;
pub mod schedule_organization_events;
pub mod schedule_organization_event_handlers;
pub mod schedule_weekday_events;
pub mod schedule_weekday_event_handlers;

pub use schedule_events::{ScheduleEvent, ScheduleEventPublisher, NoopScheduleEventPublisher};
pub use schedule_event_handlers::ScheduleEventHandler;
pub use schedule_employee_events::{ScheduleEmployeeEvent, ScheduleEmployeeEventPublisher, NoopScheduleEmployeeEventPublisher};
pub use schedule_employee_event_handlers::ScheduleEmployeeEventHandler;
pub use schedule_organization_events::{ScheduleOrganizationEvent, ScheduleOrganizationEventPublisher, NoopScheduleOrganizationEventPublisher};
pub use schedule_organization_event_handlers::ScheduleOrganizationEventHandler;
pub use schedule_weekday_events::{ScheduleWeekdayEvent, ScheduleWeekdayEventPublisher, NoopScheduleWeekdayEventPublisher};
pub use schedule_weekday_event_handlers::ScheduleWeekdayEventHandler;

// <<< CUSTOM
// END CUSTOM
