//! Domain events for ScheduleWeekday entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ScheduleWeekday;

/// Domain events for ScheduleWeekday — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ScheduleWeekday>)` variant.
pub type ScheduleWeekdayEvent = CrudEvent<ScheduleWeekday>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ScheduleWeekday events.
pub type ScheduleWeekdayEventPublisher = Arc<dyn CrudEventPublisher<ScheduleWeekday> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopScheduleWeekdayEventPublisher = NoOpCrudEventPublisher<ScheduleWeekday>;
