//! Event handler trait for ScheduleEmployee events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ScheduleEmployeeEvent;

/// Event handler for ScheduleEmployee events.
/// Implement this trait to react to ScheduleEmployee lifecycle events.
pub trait ScheduleEmployeeEventHandler: EventHandler<ScheduleEmployeeEvent> {}
