//! Domain events for ScheduleOrganization entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ScheduleOrganization;

/// Domain events for ScheduleOrganization — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ScheduleOrganization>)` variant.
pub type ScheduleOrganizationEvent = CrudEvent<ScheduleOrganization>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ScheduleOrganization events.
pub type ScheduleOrganizationEventPublisher = Arc<dyn CrudEventPublisher<ScheduleOrganization> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopScheduleOrganizationEventPublisher = NoOpCrudEventPublisher<ScheduleOrganization>;
