//! Domain events for Schedule entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Schedule;

/// Domain events for Schedule — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Schedule>)` variant.
pub type ScheduleEvent = CrudEvent<Schedule>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Schedule events.
pub type ScheduleEventPublisher = Arc<dyn CrudEventPublisher<Schedule> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopScheduleEventPublisher = NoOpCrudEventPublisher<Schedule>;
