//! Event handler trait for ScheduleWeekday events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ScheduleWeekdayEvent;

/// Event handler for ScheduleWeekday events.
/// Implement this trait to react to ScheduleWeekday lifecycle events.
pub trait ScheduleWeekdayEventHandler: EventHandler<ScheduleWeekdayEvent> {}
