//! Event handler trait for ScheduleOrganization events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ScheduleOrganizationEvent;

/// Event handler for ScheduleOrganization events.
/// Implement this trait to react to ScheduleOrganization lifecycle events.
pub trait ScheduleOrganizationEventHandler: EventHandler<ScheduleOrganizationEvent> {}
