//! Event handler trait for Schedule events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ScheduleEvent;

/// Event handler for Schedule events.
/// Implement this trait to react to Schedule lifecycle events.
pub trait ScheduleEventHandler: EventHandler<ScheduleEvent> {}
