//! Domain events for ScheduleEmployee entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ScheduleEmployee;

/// Domain events for ScheduleEmployee — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ScheduleEmployee>)` variant.
pub type ScheduleEmployeeEvent = CrudEvent<ScheduleEmployee>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ScheduleEmployee events.
pub type ScheduleEmployeeEventPublisher = Arc<dyn CrudEventPublisher<ScheduleEmployee> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopScheduleEmployeeEventPublisher = NoOpCrudEventPublisher<ScheduleEmployee>;
