//! ScheduleOrganization seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ScheduleOrganization data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// SCHEDULEORGANIZATION SEEDER
// ============================================================================

/// Seeder for schedule_organization
pub struct SeedScheduleOrganizationSeeder;

impl SeedScheduleOrganizationSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedScheduleOrganizationSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedScheduleOrganizationSeeder {
    fn name(&self) -> &'static str {
        "SeedScheduleOrganizationSeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if schedule.schedule_organizations table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM schedule.schedule_organizations")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/schedule_organization_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM schedule.schedule_organizations")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

