//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod schedule_repository;
pub mod schedule_employee_repository;
pub mod schedule_organization_repository;
pub mod schedule_weekday_repository;

// Re-exports
pub use schedule_repository::{
    ScheduleRepository,
    SchedulePaginationParams,
    SchedulePaginatedResult,
    ScheduleFilter,
};
pub use schedule_employee_repository::{
    ScheduleEmployeeRepository,
    ScheduleEmployeePaginationParams,
    ScheduleEmployeePaginatedResult,
    ScheduleEmployeeFilter,
};
pub use schedule_organization_repository::{
    ScheduleOrganizationRepository,
    ScheduleOrganizationPaginationParams,
    ScheduleOrganizationPaginatedResult,
    ScheduleOrganizationFilter,
};
pub use schedule_weekday_repository::{
    ScheduleWeekdayRepository,
    ScheduleWeekdayPaginationParams,
    ScheduleWeekdayPaginatedResult,
    ScheduleWeekdayFilter,
};
