//! Repository trait for ScheduleEmployee aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ScheduleEmployee aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::ScheduleEmployee;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ScheduleEmployeePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ScheduleEmployeePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ScheduleEmployeePaginatedResult {
    pub data: Vec<ScheduleEmployee>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ScheduleEmployeeFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
}

impl ScheduleEmployeeFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some()
    }
}

/// Repository trait for ScheduleEmployee aggregate
///
/// This trait defines the persistence contract for ScheduleEmployee entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ScheduleEmployeeRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new schedule_employee entity
    async fn save(&self, entity: &ScheduleEmployee) -> Result<ScheduleEmployee>;

    /// Find schedule_employee by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ScheduleEmployee>>;

    /// Find all schedule_employee entities
    async fn find_all(&self) -> Result<Vec<ScheduleEmployee>>;

    /// Update schedule_employee by ID
    async fn update(&self, id: &str, entity: &ScheduleEmployee) -> Result<Option<ScheduleEmployee>>;

    /// Delete schedule_employee by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List schedule_employee with pagination
    async fn list(&self, params: ScheduleEmployeePaginationParams) -> Result<ScheduleEmployeePaginatedResult>;

    /// List schedule_employee with pagination and filters
    async fn list_with_filters(&self, params: ScheduleEmployeePaginationParams, filters: ScheduleEmployeeFilter) -> Result<ScheduleEmployeePaginatedResult>;

    /// Count all schedule_employee entities
    async fn count(&self) -> Result<u64>;

    /// Count schedule_employee entities matching filters
    async fn count_with_filters(&self, filters: ScheduleEmployeeFilter) -> Result<u64>;

    /// Check if schedule_employee exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete schedule_employee by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted schedule_employee by ID
    async fn restore(&self, id: &str) -> Result<Option<ScheduleEmployee>>;

    /// List soft-deleted schedule_employee entities
    async fn list_deleted(&self, params: ScheduleEmployeePaginationParams) -> Result<ScheduleEmployeePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save schedule_employee entities
    async fn bulk_save(&self, entities: &[ScheduleEmployee]) -> Result<Vec<ScheduleEmployee>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
