//! Repository trait for ScheduleOrganization aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ScheduleOrganization aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::ScheduleOrganization;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ScheduleOrganizationPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ScheduleOrganizationPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ScheduleOrganizationPaginatedResult {
    pub data: Vec<ScheduleOrganization>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ScheduleOrganizationFilter {
    pub structure_id: Option<Uuid>,
    pub name: Option<String>,
}

impl ScheduleOrganizationFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.structure_id.is_some() || self.name.is_some()
    }
}

/// Repository trait for ScheduleOrganization aggregate
///
/// This trait defines the persistence contract for ScheduleOrganization entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ScheduleOrganizationRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new schedule_organization entity
    async fn save(&self, entity: &ScheduleOrganization) -> Result<ScheduleOrganization>;

    /// Find schedule_organization by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ScheduleOrganization>>;

    /// Find all schedule_organization entities
    async fn find_all(&self) -> Result<Vec<ScheduleOrganization>>;

    /// Update schedule_organization by ID
    async fn update(&self, id: &str, entity: &ScheduleOrganization) -> Result<Option<ScheduleOrganization>>;

    /// Delete schedule_organization by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List schedule_organization with pagination
    async fn list(&self, params: ScheduleOrganizationPaginationParams) -> Result<ScheduleOrganizationPaginatedResult>;

    /// List schedule_organization with pagination and filters
    async fn list_with_filters(&self, params: ScheduleOrganizationPaginationParams, filters: ScheduleOrganizationFilter) -> Result<ScheduleOrganizationPaginatedResult>;

    /// Count all schedule_organization entities
    async fn count(&self) -> Result<u64>;

    /// Count schedule_organization entities matching filters
    async fn count_with_filters(&self, filters: ScheduleOrganizationFilter) -> Result<u64>;

    /// Check if schedule_organization exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete schedule_organization by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted schedule_organization by ID
    async fn restore(&self, id: &str) -> Result<Option<ScheduleOrganization>>;

    /// List soft-deleted schedule_organization entities
    async fn list_deleted(&self, params: ScheduleOrganizationPaginationParams) -> Result<ScheduleOrganizationPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save schedule_organization entities
    async fn bulk_save(&self, entities: &[ScheduleOrganization]) -> Result<Vec<ScheduleOrganization>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
