//! Repository trait for Schedule aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Schedule aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::Schedule;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SchedulePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SchedulePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SchedulePaginatedResult {
    pub data: Vec<Schedule>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ScheduleFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub is_default: Option<bool>,
    pub is_override_holiday: Option<bool>,
}

impl ScheduleFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.is_default.is_some() || self.is_override_holiday.is_some()
    }
}

/// Repository trait for Schedule aggregate
///
/// This trait defines the persistence contract for Schedule entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ScheduleRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new schedule entity
    async fn save(&self, entity: &Schedule) -> Result<Schedule>;

    /// Find schedule by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Schedule>>;

    /// Find all schedule entities
    async fn find_all(&self) -> Result<Vec<Schedule>>;

    /// Update schedule by ID
    async fn update(&self, id: &str, entity: &Schedule) -> Result<Option<Schedule>>;

    /// Delete schedule by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List schedule with pagination
    async fn list(&self, params: SchedulePaginationParams) -> Result<SchedulePaginatedResult>;

    /// List schedule with pagination and filters
    async fn list_with_filters(&self, params: SchedulePaginationParams, filters: ScheduleFilter) -> Result<SchedulePaginatedResult>;

    /// Count all schedule entities
    async fn count(&self) -> Result<u64>;

    /// Count schedule entities matching filters
    async fn count_with_filters(&self, filters: ScheduleFilter) -> Result<u64>;

    /// Check if schedule exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete schedule by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted schedule by ID
    async fn restore(&self, id: &str) -> Result<Option<Schedule>>;

    /// List soft-deleted schedule entities
    async fn list_deleted(&self, params: SchedulePaginationParams) -> Result<SchedulePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save schedule entities
    async fn bulk_save(&self, entities: &[Schedule]) -> Result<Vec<Schedule>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
