//! Repository trait for ScheduleWeekday aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ScheduleWeekday aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{ScheduleWeekday, WeekdayType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ScheduleWeekdayPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ScheduleWeekdayPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ScheduleWeekdayPaginatedResult {
    pub data: Vec<ScheduleWeekday>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ScheduleWeekdayFilter {
    pub schedule_id: Option<Uuid>,
    pub sun: Option<WeekdayType>,
    pub mon: Option<WeekdayType>,
    pub tue: Option<WeekdayType>,
    pub wed: Option<WeekdayType>,
    pub thu: Option<WeekdayType>,
    pub fri: Option<WeekdayType>,
    pub sat: Option<WeekdayType>,
}

impl ScheduleWeekdayFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.schedule_id.is_some() || self.sun.is_some() || self.mon.is_some() || self.tue.is_some() || self.wed.is_some() || self.thu.is_some() || self.fri.is_some() || self.sat.is_some()
    }
}

/// Repository trait for ScheduleWeekday aggregate
///
/// This trait defines the persistence contract for ScheduleWeekday entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ScheduleWeekdayRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new schedule_weekday entity
    async fn save(&self, entity: &ScheduleWeekday) -> Result<ScheduleWeekday>;

    /// Find schedule_weekday by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ScheduleWeekday>>;

    /// Find all schedule_weekday entities
    async fn find_all(&self) -> Result<Vec<ScheduleWeekday>>;

    /// Update schedule_weekday by ID
    async fn update(&self, id: &str, entity: &ScheduleWeekday) -> Result<Option<ScheduleWeekday>>;

    /// Delete schedule_weekday by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List schedule_weekday with pagination
    async fn list(&self, params: ScheduleWeekdayPaginationParams) -> Result<ScheduleWeekdayPaginatedResult>;

    /// List schedule_weekday with pagination and filters
    async fn list_with_filters(&self, params: ScheduleWeekdayPaginationParams, filters: ScheduleWeekdayFilter) -> Result<ScheduleWeekdayPaginatedResult>;

    /// Count all schedule_weekday entities
    async fn count(&self) -> Result<u64>;

    /// Count schedule_weekday entities matching filters
    async fn count_with_filters(&self, filters: ScheduleWeekdayFilter) -> Result<u64>;

    /// Check if schedule_weekday exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete schedule_weekday by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted schedule_weekday by ID
    async fn restore(&self, id: &str) -> Result<Option<ScheduleWeekday>>;

    /// List soft-deleted schedule_weekday entities
    async fn list_deleted(&self, params: ScheduleWeekdayPaginationParams) -> Result<ScheduleWeekdayPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save schedule_weekday entities
    async fn bulk_save(&self, entities: &[ScheduleWeekday]) -> Result<Vec<ScheduleWeekday>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
