//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod schedule_repository;
mod schedule_employee_repository;
mod schedule_organization_repository;
mod schedule_weekday_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use schedule_repository::ScheduleRepository;
pub use schedule_employee_repository::ScheduleEmployeeRepository;
pub use schedule_organization_repository::ScheduleOrganizationRepository;
pub use schedule_weekday_repository::ScheduleWeekdayRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
