//! Repository for ScheduleEmployee entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ScheduleEmployee, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ScheduleEmployee;

/// Table name for ScheduleEmployee entities
pub const TABLE_NAME: &str = "schedule.schedule_employees";

/// Repository for ScheduleEmployee entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ScheduleEmployeeRepository(
    backbone_orm::GenericCrudRepository<ScheduleEmployee, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ScheduleEmployeeRepository {
    type Target = backbone_orm::GenericCrudRepository<ScheduleEmployee, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ScheduleEmployeeRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ScheduleEmployeeRepository, ScheduleEmployee, soft_delete);
