//! Repository for Schedule entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Schedule, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Schedule;

/// Table name for Schedule entities
pub const TABLE_NAME: &str = "schedule.schedules";

/// Repository for Schedule entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ScheduleRepository(
    backbone_orm::GenericCrudRepository<Schedule, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ScheduleRepository {
    type Target = backbone_orm::GenericCrudRepository<Schedule, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ScheduleRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ScheduleRepository, Schedule, soft_delete);
