//! Repository for ScheduleWeekday entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ScheduleWeekday, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ScheduleWeekday;

/// Table name for ScheduleWeekday entities
pub const TABLE_NAME: &str = "schedule.schedule_weekdays";

/// Repository for ScheduleWeekday entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ScheduleWeekdayRepository(
    backbone_orm::GenericCrudRepository<ScheduleWeekday, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ScheduleWeekdayRepository {
    type Target = backbone_orm::GenericCrudRepository<ScheduleWeekday, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ScheduleWeekdayRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ScheduleWeekdayRepository, ScheduleWeekday, soft_delete);
