//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod schedule_validator;
pub mod schedule_employee_validator;
pub mod schedule_organization_validator;
pub mod schedule_weekday_validator;

pub use schedule_validator::{ScheduleValidator, schedule_validator};
pub use schedule_employee_validator::{ScheduleEmployeeValidator, schedule_employee_validator};
pub use schedule_organization_validator::{ScheduleOrganizationValidator, schedule_organization_validator};
pub use schedule_weekday_validator::{ScheduleWeekdayValidator, schedule_weekday_validator};

// <<< CUSTOM
// END CUSTOM
