//! Validator for ScheduleOrganization entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ScheduleOrganization>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::ScheduleOrganization;

/// Validator type alias for ScheduleOrganization entities.
pub type ScheduleOrganizationValidator = EntityValidator<ScheduleOrganization>;

/// Build a validator for ScheduleOrganization with all schema-defined field rules.
pub fn schedule_organization_validator() -> ScheduleOrganizationValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("name", |e: &ScheduleOrganization| e.name.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
