//! Validator for Schedule entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Schedule>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::Schedule;

/// Validator type alias for Schedule entities.
pub type ScheduleValidator = EntityValidator<Schedule>;

/// Build a validator for Schedule with all schema-defined field rules.
pub fn schedule_validator() -> ScheduleValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &Schedule| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
