//! Validator for ScheduleEmployee entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ScheduleEmployee>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::ScheduleEmployee;

/// Validator type alias for ScheduleEmployee entities.
pub type ScheduleEmployeeValidator = EntityValidator<ScheduleEmployee>;

/// Build a validator for ScheduleEmployee with all schema-defined field rules.
pub fn schedule_employee_validator() -> ScheduleEmployeeValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
