//! Validator for ScheduleWeekday entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ScheduleWeekday>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::ScheduleWeekday;

/// Validator type alias for ScheduleWeekday entities.
pub type ScheduleWeekdayValidator = EntityValidator<ScheduleWeekday>;

/// Build a validator for ScheduleWeekday with all schema-defined field rules.
pub fn schedule_weekday_validator() -> ScheduleWeekdayValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
