//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod schedule_auth;
pub mod schedule_employee_auth;
pub mod schedule_organization_auth;
pub mod schedule_weekday_auth;

pub use schedule_auth::{SchedulePolicy, ScheduleGuard, ScheduleServiceGuard};
pub use schedule_employee_auth::{ScheduleEmployeePolicy, ScheduleEmployeeGuard, ScheduleEmployeeServiceGuard};
pub use schedule_organization_auth::{ScheduleOrganizationPolicy, ScheduleOrganizationGuard, ScheduleOrganizationServiceGuard};
pub use schedule_weekday_auth::{ScheduleWeekdayPolicy, ScheduleWeekdayGuard, ScheduleWeekdayServiceGuard};

// <<< CUSTOM
// END CUSTOM
