//! Auth configuration for Schedule handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Schedule>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ScheduleService;
use crate::domain::entity::Schedule;

/// Permission string constants for Schedule operations.
pub mod permissions {
    pub const LIST:        &str = "schedule:list";
    pub const READ:        &str = "schedule:read";
    pub const CREATE:      &str = "schedule:create";
    pub const UPDATE:      &str = "schedule:update";
    pub const DELETE:      &str = "schedule:delete";
    pub const RESTORE:     &str = "schedule:restore";
    pub const TRASH:       &str = "schedule:trash";
    pub const EMPTY_TRASH: &str = "schedule:empty_trash";
    pub const BULK_CREATE: &str = "schedule:bulk_create";
    pub const UPSERT:      &str = "schedule:upsert";
}

/// Resource policy for Schedule — maps CRUD actions to permission strings.
pub struct SchedulePolicy;

#[async_trait]
impl ResourcePolicy<Schedule> for SchedulePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Schedule,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Schedule handlers.
///
/// Wraps `ScheduleService` and checks `SchedulePolicy` before delegating.
pub type ScheduleGuard = PermissionGuard<Schedule>;

/// Service-integrated permission guard for Schedule (for use in generated handlers).
pub type ScheduleServiceGuard = ServicePermissionGuard<Schedule, ScheduleService, SchedulePolicy>;

// <<< CUSTOM
// END CUSTOM
