//! Auth configuration for ScheduleEmployee handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ScheduleEmployee>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ScheduleEmployeeService;
use crate::domain::entity::ScheduleEmployee;

/// Permission string constants for ScheduleEmployee operations.
pub mod permissions {
    pub const LIST:        &str = "schedule_employee:list";
    pub const READ:        &str = "schedule_employee:read";
    pub const CREATE:      &str = "schedule_employee:create";
    pub const UPDATE:      &str = "schedule_employee:update";
    pub const DELETE:      &str = "schedule_employee:delete";
    pub const RESTORE:     &str = "schedule_employee:restore";
    pub const TRASH:       &str = "schedule_employee:trash";
    pub const EMPTY_TRASH: &str = "schedule_employee:empty_trash";
    pub const BULK_CREATE: &str = "schedule_employee:bulk_create";
    pub const UPSERT:      &str = "schedule_employee:upsert";
}

/// Resource policy for ScheduleEmployee — maps CRUD actions to permission strings.
pub struct ScheduleEmployeePolicy;

#[async_trait]
impl ResourcePolicy<ScheduleEmployee> for ScheduleEmployeePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ScheduleEmployee,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ScheduleEmployee handlers.
///
/// Wraps `ScheduleEmployeeService` and checks `ScheduleEmployeePolicy` before delegating.
pub type ScheduleEmployeeGuard = PermissionGuard<ScheduleEmployee>;

/// Service-integrated permission guard for ScheduleEmployee (for use in generated handlers).
pub type ScheduleEmployeeServiceGuard = ServicePermissionGuard<ScheduleEmployee, ScheduleEmployeeService, ScheduleEmployeePolicy>;

// <<< CUSTOM
// END CUSTOM
