//! Auth configuration for ScheduleWeekday handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ScheduleWeekday>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ScheduleWeekdayService;
use crate::domain::entity::ScheduleWeekday;

/// Permission string constants for ScheduleWeekday operations.
pub mod permissions {
    pub const LIST:        &str = "schedule_weekday:list";
    pub const READ:        &str = "schedule_weekday:read";
    pub const CREATE:      &str = "schedule_weekday:create";
    pub const UPDATE:      &str = "schedule_weekday:update";
    pub const DELETE:      &str = "schedule_weekday:delete";
    pub const RESTORE:     &str = "schedule_weekday:restore";
    pub const TRASH:       &str = "schedule_weekday:trash";
    pub const EMPTY_TRASH: &str = "schedule_weekday:empty_trash";
    pub const BULK_CREATE: &str = "schedule_weekday:bulk_create";
    pub const UPSERT:      &str = "schedule_weekday:upsert";
}

/// Resource policy for ScheduleWeekday — maps CRUD actions to permission strings.
pub struct ScheduleWeekdayPolicy;

#[async_trait]
impl ResourcePolicy<ScheduleWeekday> for ScheduleWeekdayPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ScheduleWeekday,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ScheduleWeekday handlers.
///
/// Wraps `ScheduleWeekdayService` and checks `ScheduleWeekdayPolicy` before delegating.
pub type ScheduleWeekdayGuard = PermissionGuard<ScheduleWeekday>;

/// Service-integrated permission guard for ScheduleWeekday (for use in generated handlers).
pub type ScheduleWeekdayServiceGuard = ServicePermissionGuard<ScheduleWeekday, ScheduleWeekdayService, ScheduleWeekdayPolicy>;

// <<< CUSTOM
// END CUSTOM
