//! Auth configuration for ScheduleOrganization handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ScheduleOrganization>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ScheduleOrganizationService;
use crate::domain::entity::ScheduleOrganization;

/// Permission string constants for ScheduleOrganization operations.
pub mod permissions {
    pub const LIST:        &str = "schedule_organization:list";
    pub const READ:        &str = "schedule_organization:read";
    pub const CREATE:      &str = "schedule_organization:create";
    pub const UPDATE:      &str = "schedule_organization:update";
    pub const DELETE:      &str = "schedule_organization:delete";
    pub const RESTORE:     &str = "schedule_organization:restore";
    pub const TRASH:       &str = "schedule_organization:trash";
    pub const EMPTY_TRASH: &str = "schedule_organization:empty_trash";
    pub const BULK_CREATE: &str = "schedule_organization:bulk_create";
    pub const UPSERT:      &str = "schedule_organization:upsert";
}

/// Resource policy for ScheduleOrganization — maps CRUD actions to permission strings.
pub struct ScheduleOrganizationPolicy;

#[async_trait]
impl ResourcePolicy<ScheduleOrganization> for ScheduleOrganizationPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ScheduleOrganization,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ScheduleOrganization handlers.
///
/// Wraps `ScheduleOrganizationService` and checks `ScheduleOrganizationPolicy` before delegating.
pub type ScheduleOrganizationGuard = PermissionGuard<ScheduleOrganization>;

/// Service-integrated permission guard for ScheduleOrganization (for use in generated handlers).
pub type ScheduleOrganizationServiceGuard = ServicePermissionGuard<ScheduleOrganization, ScheduleOrganizationService, ScheduleOrganizationPolicy>;

// <<< CUSTOM
// END CUSTOM
