//! ScheduleWeekday API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the ScheduleWeekday CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SCHEDULEWEEKDAY TEST DATA GENERATOR
// ============================================================================

/// Test data generator for ScheduleWeekday
pub struct ScheduleWeekdayTestData;

impl TestDataGenerator for ScheduleWeekdayTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "schedule_id": Uuid::new_v4().to_string(),
            "sun": "weekday",
            "mon": "weekday",
            "tue": "weekday",
            "wed": "weekday",
            "thu": "weekday",
            "fri": "weekday",
            "sat": "weekday",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "schedule_id": Uuid::new_v4().to_string(),
            "sun": "weekday",
            "mon": "weekday",
            "tue": "weekday",
            "wed": "weekday",
            "thu": "weekday",
            "fri": "weekday",
            "sat": "weekday",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/schedules", &super::schedule_api_test::ScheduleTestData).await {
            deps.push(("schedule_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// SCHEDULEWEEKDAY API TEST
// ============================================================================

/// ScheduleWeekday API test suite
pub struct ScheduleWeekdayApiTest {
    inner: GenericCrudTest<ScheduleWeekdayTestData>,
}

impl ScheduleWeekdayApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/schedule_weekdays", "ScheduleWeekday");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ScheduleWeekdayTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ScheduleWeekdayApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_schedule_weekday_crud() {
        let mut test = ScheduleWeekdayApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add ScheduleWeekday specific tests here
// <<< CUSTOM TESTS END >>>
