//! Schedule API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Schedule CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SCHEDULE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Schedule
pub struct ScheduleTestData;

impl TestDataGenerator for ScheduleTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "is_default": false,
            "order_number": 1,
            "start_date": null,
            "end_date": null,
            "time_in": "12:00:00",
            "time_out": "12:00:00",
            "is_override_holiday": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "is_default": false,
            "order_number": 1,
            "start_date": null,
            "end_date": null,
            "time_in": "12:00:00",
            "time_out": "12:00:00",
            "is_override_holiday": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// SCHEDULE API TEST
// ============================================================================

/// Schedule API test suite
pub struct ScheduleApiTest {
    inner: GenericCrudTest<ScheduleTestData>,
}

impl ScheduleApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/schedules", "Schedule");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ScheduleTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ScheduleApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_schedule_crud() {
        let mut test = ScheduleApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Schedule specific tests here
// <<< CUSTOM TESTS END >>>
