//! Schedule Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::ScheduleService;
use crate::application::service::ScheduleEmployeeService;
use crate::application::service::ScheduleOrganizationService;
use crate::application::service::ScheduleWeekdayService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Schedule service
    pub schedule_service: Arc<ScheduleService>,
    /// ScheduleEmployee service
    pub schedule_employee_service: Arc<ScheduleEmployeeService>,
    /// ScheduleOrganization service
    pub schedule_organization_service: Arc<ScheduleOrganizationService>,
    /// ScheduleWeekday service
    pub schedule_weekday_service: Arc<ScheduleWeekdayService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        schedule_service: Arc<ScheduleService>,
        schedule_employee_service: Arc<ScheduleEmployeeService>,
        schedule_organization_service: Arc<ScheduleOrganizationService>,
        schedule_weekday_service: Arc<ScheduleWeekdayService>
    ) -> Self {
        Self {
            schedule_service,
            schedule_employee_service,
            schedule_organization_service,
            schedule_weekday_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::ScheduleModule) -> Self {
        Self {
            schedule_service: module.schedule_service.clone(),
            schedule_employee_service: module.schedule_employee_service.clone(),
            schedule_organization_service: module.schedule_organization_service.clone(),
            schedule_weekday_service: module.schedule_weekday_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    schedule_service: Option<Arc<ScheduleService>>,
    schedule_employee_service: Option<Arc<ScheduleEmployeeService>>,
    schedule_organization_service: Option<Arc<ScheduleOrganizationService>>,
    schedule_weekday_service: Option<Arc<ScheduleWeekdayService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Schedule service.
    pub fn with_schedule_service(mut self, service: Arc<ScheduleService>) -> Self {
        self.schedule_service = Some(service);
        self
    }

    /// Set the ScheduleEmployee service.
    pub fn with_schedule_employee_service(mut self, service: Arc<ScheduleEmployeeService>) -> Self {
        self.schedule_employee_service = Some(service);
        self
    }

    /// Set the ScheduleOrganization service.
    pub fn with_schedule_organization_service(mut self, service: Arc<ScheduleOrganizationService>) -> Self {
        self.schedule_organization_service = Some(service);
        self
    }

    /// Set the ScheduleWeekday service.
    pub fn with_schedule_weekday_service(mut self, service: Arc<ScheduleWeekdayService>) -> Self {
        self.schedule_weekday_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            schedule_service: self.schedule_service.expect("schedule_service is required"),
            schedule_employee_service: self.schedule_employee_service.expect("schedule_employee_service is required"),
            schedule_organization_service: self.schedule_organization_service.expect("schedule_organization_service is required"),
            schedule_weekday_service: self.schedule_weekday_service.expect("schedule_weekday_service is required"),
        }
    }
}
