//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    schedule_handler::create_schedule_routes,
    schedule_employee_handler::create_schedule_employee_routes,
    schedule_organization_handler::create_schedule_organization_routes,
    schedule_weekday_handler::create_schedule_weekday_routes,
};

use crate::application::service::{
    ScheduleService,
    ScheduleEmployeeService,
    ScheduleOrganizationService,
    ScheduleWeekdayService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub schedule: Arc<ScheduleService>,
    pub schedule_employee: Arc<ScheduleEmployeeService>,
    pub schedule_organization: Arc<ScheduleOrganizationService>,
    pub schedule_weekday: Arc<ScheduleWeekdayService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // Schedule routes (12 Backbone endpoints)
        .merge(create_schedule_routes(services.schedule))
        // ScheduleEmployee routes (12 Backbone endpoints)
        .merge(create_schedule_employee_routes(services.schedule_employee))
        // ScheduleOrganization routes (12 Backbone endpoints)
        .merge(create_schedule_organization_routes(services.schedule_organization))
        // ScheduleWeekday routes (12 Backbone endpoints)
        .merge(create_schedule_weekday_routes(services.schedule_weekday))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn schedule_routes(service: Arc<ScheduleService>) -> Router {
        create_schedule_routes(service)
    }

    pub fn schedule_employee_routes(service: Arc<ScheduleEmployeeService>) -> Router {
        create_schedule_employee_routes(service)
    }

    pub fn schedule_organization_routes(service: Arc<ScheduleOrganizationService>) -> Router {
        create_schedule_organization_routes(service)
    }

    pub fn schedule_weekday_routes(service: Arc<ScheduleWeekdayService>) -> Router {
        create_schedule_weekday_routes(service)
    }

}
