//! Public events for Schedule module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// SCHEDULE EVENTS
// ============================================================================

/// Event published when a Schedule is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScheduleCreatedEvent {
    pub id: ScheduleId,
    pub data: ScheduleDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Schedule is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScheduleUpdatedEvent {
    pub id: ScheduleId,
    pub data: ScheduleDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Schedule is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScheduleDeletedEvent {
    pub id: ScheduleId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SCHEDULEEMPLOYEE EVENTS
// ============================================================================

/// Event published when a ScheduleEmployee is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScheduleEmployeeCreatedEvent {
    pub id: ScheduleEmployeeId,
    pub data: ScheduleEmployeeDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ScheduleEmployee is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScheduleEmployeeUpdatedEvent {
    pub id: ScheduleEmployeeId,
    pub data: ScheduleEmployeeDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ScheduleEmployee is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScheduleEmployeeDeletedEvent {
    pub id: ScheduleEmployeeId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SCHEDULEORGANIZATION EVENTS
// ============================================================================

/// Event published when a ScheduleOrganization is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScheduleOrganizationCreatedEvent {
    pub id: ScheduleOrganizationId,
    pub data: ScheduleOrganizationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ScheduleOrganization is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScheduleOrganizationUpdatedEvent {
    pub id: ScheduleOrganizationId,
    pub data: ScheduleOrganizationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ScheduleOrganization is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScheduleOrganizationDeletedEvent {
    pub id: ScheduleOrganizationId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SCHEDULEWEEKDAY EVENTS
// ============================================================================

/// Event published when a ScheduleWeekday is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScheduleWeekdayCreatedEvent {
    pub id: ScheduleWeekdayId,
    pub data: ScheduleWeekdayDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ScheduleWeekday is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScheduleWeekdayUpdatedEvent {
    pub id: ScheduleWeekdayId,
    pub data: ScheduleWeekdayDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ScheduleWeekday is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScheduleWeekdayDeletedEvent {
    pub id: ScheduleWeekdayId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Schedule module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ScheduleEvent {
    ScheduleCreated(ScheduleCreatedEvent),
    ScheduleUpdated(ScheduleUpdatedEvent),
    ScheduleDeleted(ScheduleDeletedEvent),
    ScheduleEmployeeCreated(ScheduleEmployeeCreatedEvent),
    ScheduleEmployeeUpdated(ScheduleEmployeeUpdatedEvent),
    ScheduleEmployeeDeleted(ScheduleEmployeeDeletedEvent),
    ScheduleOrganizationCreated(ScheduleOrganizationCreatedEvent),
    ScheduleOrganizationUpdated(ScheduleOrganizationUpdatedEvent),
    ScheduleOrganizationDeleted(ScheduleOrganizationDeletedEvent),
    ScheduleWeekdayCreated(ScheduleWeekdayCreatedEvent),
    ScheduleWeekdayUpdated(ScheduleWeekdayUpdatedEvent),
    ScheduleWeekdayDeleted(ScheduleWeekdayDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScheduleEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for ScheduleEventMetadata {
    fn default() -> Self {
        Self {
            module: "schedule",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
