//! Schedule Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Schedule exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use schedule::exports::{ScheduleDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `ScheduleDto` - Data transfer object for Schedule
/// - `ScheduleSummary` - Summary view of Schedule
/// - `ScheduleId` - Type-safe ID wrapper
/// - `ScheduleEmployeeDto` - Data transfer object for ScheduleEmployee
/// - `ScheduleEmployeeSummary` - Summary view of ScheduleEmployee
/// - `ScheduleEmployeeId` - Type-safe ID wrapper
/// - `ScheduleOrganizationDto` - Data transfer object for ScheduleOrganization
/// - `ScheduleOrganizationSummary` - Summary view of ScheduleOrganization
/// - `ScheduleOrganizationId` - Type-safe ID wrapper
/// - `ScheduleWeekdayDto` - Data transfer object for ScheduleWeekday
/// - `ScheduleWeekdaySummary` - Summary view of ScheduleWeekday
/// - `ScheduleWeekdayId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `ScheduleCreatedEvent` - Published when Schedule is created
/// - `ScheduleUpdatedEvent` - Published when Schedule is updated
/// - `ScheduleDeletedEvent` - Published when Schedule is deleted
/// - `ScheduleEmployeeCreatedEvent` - Published when ScheduleEmployee is created
/// - `ScheduleEmployeeUpdatedEvent` - Published when ScheduleEmployee is updated
/// - `ScheduleEmployeeDeletedEvent` - Published when ScheduleEmployee is deleted
/// - `ScheduleOrganizationCreatedEvent` - Published when ScheduleOrganization is created
/// - `ScheduleOrganizationUpdatedEvent` - Published when ScheduleOrganization is updated
/// - `ScheduleOrganizationDeletedEvent` - Published when ScheduleOrganization is deleted
/// - `ScheduleWeekdayCreatedEvent` - Published when ScheduleWeekday is created
/// - `ScheduleWeekdayUpdatedEvent` - Published when ScheduleWeekday is updated
/// - `ScheduleWeekdayDeletedEvent` - Published when ScheduleWeekday is deleted
pub struct ExportSummary;
