//! Public services for Schedule module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Schedule module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait ScheduleQueryService: Send + Sync {
    /// Get Schedule by ID
    async fn get_schedule(&self, id: ScheduleId) -> Result<Option<ScheduleDto>>;

    /// Get Schedule summary by ID
    async fn get_schedule_summary(&self, id: ScheduleId) -> Result<Option<ScheduleSummary>>;

    /// Check if Schedule exists
    async fn schedule_exists(&self, id: ScheduleId) -> Result<bool>;

    /// Get ScheduleEmployee by ID
    async fn get_schedule_employee(&self, id: ScheduleEmployeeId) -> Result<Option<ScheduleEmployeeDto>>;

    /// Get ScheduleEmployee summary by ID
    async fn get_schedule_employee_summary(&self, id: ScheduleEmployeeId) -> Result<Option<ScheduleEmployeeSummary>>;

    /// Check if ScheduleEmployee exists
    async fn schedule_employee_exists(&self, id: ScheduleEmployeeId) -> Result<bool>;

    /// Get ScheduleOrganization by ID
    async fn get_schedule_organization(&self, id: ScheduleOrganizationId) -> Result<Option<ScheduleOrganizationDto>>;

    /// Get ScheduleOrganization summary by ID
    async fn get_schedule_organization_summary(&self, id: ScheduleOrganizationId) -> Result<Option<ScheduleOrganizationSummary>>;

    /// Check if ScheduleOrganization exists
    async fn schedule_organization_exists(&self, id: ScheduleOrganizationId) -> Result<bool>;

    /// Get ScheduleWeekday by ID
    async fn get_schedule_weekday(&self, id: ScheduleWeekdayId) -> Result<Option<ScheduleWeekdayDto>>;

    /// Get ScheduleWeekday summary by ID
    async fn get_schedule_weekday_summary(&self, id: ScheduleWeekdayId) -> Result<Option<ScheduleWeekdaySummary>>;

    /// Check if ScheduleWeekday exists
    async fn schedule_weekday_exists(&self, id: ScheduleWeekdayId) -> Result<bool>;

}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
