//! Schedule Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::ScheduleService;
pub use application::service::ScheduleEmployeeService;
pub use application::service::ScheduleOrganizationService;
pub use application::service::ScheduleWeekdayService;

// Re-exports - Workflows
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Schedule module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let schedule = ScheduleModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = schedule.all_crud_routes();
/// ```
pub struct ScheduleModule {
    pub(crate) schedule_service: Arc<ScheduleService>,
    pub(crate) schedule_employee_service: Arc<ScheduleEmployeeService>,
    pub(crate) schedule_organization_service: Arc<ScheduleOrganizationService>,
    pub(crate) schedule_weekday_service: Arc<ScheduleWeekdayService>,
    // <<< CUSTOM FIELDS
    // END CUSTOM
}

impl ScheduleModule {
    /// Create a new module builder
    pub fn builder() -> ScheduleModuleBuilder {
        ScheduleModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_schedule_routes,
            create_schedule_employee_routes,
            create_schedule_organization_routes,
            create_schedule_weekday_routes,
        };

        Router::new()
            .merge(create_schedule_routes(self.schedule_service.clone()))
            .merge(create_schedule_employee_routes(self.schedule_employee_service.clone()))
            .merge(create_schedule_organization_routes(self.schedule_organization_service.clone()))
            .merge(create_schedule_weekday_routes(self.schedule_weekday_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for ScheduleModule
pub struct ScheduleModuleBuilder {
    db_pool: Option<PgPool>,
}

impl ScheduleModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<ScheduleModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Schedule service
        let schedule_repository = Arc::new(ScheduleRepository::new(db_pool.clone()));
        let schedule_service = Arc::new(ScheduleService::with_repository(schedule_repository.clone()));

        // ScheduleEmployee service
        let schedule_employee_repository = Arc::new(ScheduleEmployeeRepository::new(db_pool.clone()));
        let schedule_employee_service = Arc::new(ScheduleEmployeeService::with_repository(schedule_employee_repository.clone()));

        // ScheduleOrganization service
        let schedule_organization_repository = Arc::new(ScheduleOrganizationRepository::new(db_pool.clone()));
        let schedule_organization_service = Arc::new(ScheduleOrganizationService::with_repository(schedule_organization_repository.clone()));

        // ScheduleWeekday service
        let schedule_weekday_repository = Arc::new(ScheduleWeekdayRepository::new(db_pool.clone()));
        let schedule_weekday_service = Arc::new(ScheduleWeekdayService::with_repository(schedule_weekday_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(ScheduleModule {
            schedule_service,
            schedule_employee_service,
            schedule_organization_service,
            schedule_weekday_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for ScheduleModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
