//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod schedule_usecases;
pub mod schedule_employee_usecases;
pub mod schedule_organization_usecases;
pub mod schedule_weekday_usecases;

pub use schedule_usecases::{
    CreateScheduleUseCase, UpdateScheduleUseCase, GetScheduleUseCase,
    DeleteScheduleUseCase, ListScheduleUseCase,
};
pub use schedule_employee_usecases::{
    CreateScheduleEmployeeUseCase, UpdateScheduleEmployeeUseCase, GetScheduleEmployeeUseCase,
    DeleteScheduleEmployeeUseCase, ListScheduleEmployeeUseCase,
};
pub use schedule_organization_usecases::{
    CreateScheduleOrganizationUseCase, UpdateScheduleOrganizationUseCase, GetScheduleOrganizationUseCase,
    DeleteScheduleOrganizationUseCase, ListScheduleOrganizationUseCase,
};
pub use schedule_weekday_usecases::{
    CreateScheduleWeekdayUseCase, UpdateScheduleWeekdayUseCase, GetScheduleWeekdayUseCase,
    DeleteScheduleWeekdayUseCase, ListScheduleWeekdayUseCase,
};

// <<< CUSTOM
// END CUSTOM
