//! Use case type aliases for Schedule aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateScheduleDto, UpdateScheduleDto};
use crate::application::service::ScheduleService;
use crate::domain::entity::Schedule;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateScheduleUseCase = CreateUseCase<Schedule, CreateScheduleDto, ScheduleService>;
pub type UpdateScheduleUseCase = UpdateUseCase<Schedule, UpdateScheduleDto, ScheduleService>;
pub type GetScheduleUseCase    = GetUseCase<Schedule, ScheduleService>;
pub type DeleteScheduleUseCase = DeleteUseCase<Schedule, ScheduleService>;
pub type ListScheduleUseCase   = ListUseCase<Schedule, ScheduleService>;

// <<< CUSTOM
// END CUSTOM
