//! Use case type aliases for ScheduleWeekday aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateScheduleWeekdayDto, UpdateScheduleWeekdayDto};
use crate::application::service::ScheduleWeekdayService;
use crate::domain::entity::ScheduleWeekday;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateScheduleWeekdayUseCase = CreateUseCase<ScheduleWeekday, CreateScheduleWeekdayDto, ScheduleWeekdayService>;
pub type UpdateScheduleWeekdayUseCase = UpdateUseCase<ScheduleWeekday, UpdateScheduleWeekdayDto, ScheduleWeekdayService>;
pub type GetScheduleWeekdayUseCase    = GetUseCase<ScheduleWeekday, ScheduleWeekdayService>;
pub type DeleteScheduleWeekdayUseCase = DeleteUseCase<ScheduleWeekday, ScheduleWeekdayService>;
pub type ListScheduleWeekdayUseCase   = ListUseCase<ScheduleWeekday, ScheduleWeekdayService>;

// <<< CUSTOM
// END CUSTOM
