//! Use case type aliases for ScheduleEmployee aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateScheduleEmployeeDto, UpdateScheduleEmployeeDto};
use crate::application::service::ScheduleEmployeeService;
use crate::domain::entity::ScheduleEmployee;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateScheduleEmployeeUseCase = CreateUseCase<ScheduleEmployee, CreateScheduleEmployeeDto, ScheduleEmployeeService>;
pub type UpdateScheduleEmployeeUseCase = UpdateUseCase<ScheduleEmployee, UpdateScheduleEmployeeDto, ScheduleEmployeeService>;
pub type GetScheduleEmployeeUseCase    = GetUseCase<ScheduleEmployee, ScheduleEmployeeService>;
pub type DeleteScheduleEmployeeUseCase = DeleteUseCase<ScheduleEmployee, ScheduleEmployeeService>;
pub type ListScheduleEmployeeUseCase   = ListUseCase<ScheduleEmployee, ScheduleEmployeeService>;

// <<< CUSTOM
// END CUSTOM
