//! Use case type aliases for ScheduleOrganization aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateScheduleOrganizationDto, UpdateScheduleOrganizationDto};
use crate::application::service::ScheduleOrganizationService;
use crate::domain::entity::ScheduleOrganization;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateScheduleOrganizationUseCase = CreateUseCase<ScheduleOrganization, CreateScheduleOrganizationDto, ScheduleOrganizationService>;
pub type UpdateScheduleOrganizationUseCase = UpdateUseCase<ScheduleOrganization, UpdateScheduleOrganizationDto, ScheduleOrganizationService>;
pub type GetScheduleOrganizationUseCase    = GetUseCase<ScheduleOrganization, ScheduleOrganizationService>;
pub type DeleteScheduleOrganizationUseCase = DeleteUseCase<ScheduleOrganization, ScheduleOrganizationService>;
pub type ListScheduleOrganizationUseCase   = ListUseCase<ScheduleOrganization, ScheduleOrganizationService>;

// <<< CUSTOM
// END CUSTOM
