//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod schedule_handler;
pub mod schedule_employee_handler;
pub mod schedule_organization_handler;
pub mod schedule_weekday_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use schedule_handler::{create_schedule_routes, create_schedule_read_routes, create_schedule_write_routes};
pub use schedule_employee_handler::{create_schedule_employee_routes, create_schedule_employee_read_routes, create_schedule_employee_write_routes};
pub use schedule_organization_handler::{create_schedule_organization_routes, create_schedule_organization_read_routes, create_schedule_organization_write_routes};
pub use schedule_weekday_handler::{create_schedule_weekday_routes, create_schedule_weekday_read_routes, create_schedule_weekday_write_routes};
// <<< CUSTOM
// END CUSTOM
